Repository Hakondate/Hakondate, pull requests merged in 2023-02, with the labels that each got.

#98 fix typo
  .vscode/settings.json
Labels: bug

#84 ClashlyticsとAnalyticsの収集
  android/app/build.gradle
  android/app/src/firebase/dev/google-services.json
  android/build.gradle
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Info-Debug.plist
  ios/Runner/Info-Release.plist
  lib/main.dart
  lib/model/menu/menu_model.dart
  lib/util/analytics_controller.dart
  lib/util/environment.dart
  lib/util/exception/class_type_exception.dart
  lib/view/daily/menu_card.dart
  lib/view/daily/nutrients_card.dart
  lib/view/signup/signup.dart
  lib/view_model/multi_page/common_function.dart
  lib/view_model/multi_page/user_view_model.dart
  lib/view_model/single_page/daily_view_model.dart
  pubspec.lock
  pubspec.yaml
Labels: documentation, enhancement, signup, challenge, Navigation

#88 レシピ画面の実装
  assets/images/status/error.png
  assets/images/status/menu_status/holiday.png
  assets/images/status/menu_status/no_data.png
  ios/Podfile
  lib/constant/app_color.dart
  lib/constant/open_data_recipes.dart
  lib/constant/size.dart
  lib/main.dart
  lib/model/recipe/open_data_recipe_model.dart
  lib/model/recipe/open_data_recipe_model.freezed.dart
  lib/model/recipe/recipe_type.dart
  lib/repository/local/directory/open_data_recipe_local_repository.dart
  lib/repository/local/sqlite/local_database.dart
  lib/repository/local/sqlite/local_database.g.dart
  lib/repository/local/sqlite/menus_local_repository.dart
  lib/repository/local/sqlite/schools_local_repository.dart
  lib/repository/local/sqlite/table/dish_foodstuffs_table.dart
  lib/repository/local/sqlite/table/dishes_table.dart
  lib/repository/local/sqlite/table/foodstuffs_table.dart
  lib/repository/local/sqlite/table/menu_dishes_table.dart
  lib/repository/local/sqlite/table/menus_table.dart
  lib/repository/local/sqlite/table/schools_table.dart
  lib/repository/local/sqlite/table/users_table.dart
  lib/repository/local/sqlite/users_local_repository.dart
  lib/repository/remote/open_data_recipe_remote_repository.dart
  lib/router/routes.dart
  lib/util/exception/local_directory_exception.dart
  lib/view/component/dialog/exception_dialog/download_exception_dialog.dart
  lib/view/daily/menu_card.dart
  lib/view/daily/non_lunches_day_body.dart
  lib/view/recipe/open_data_recipe_grid.dart
  lib/view/recipe/open_data_recipe_header.dart
  lib/view/recipe/recipe.dart
  lib/view/recipe/recipe_pdf.dart
  lib/view_model/multi_page/common_function.dart
  lib/view_model/multi_page/user_view_model.dart
  lib/view_model/single_page/calendar_view_model.dart
  lib/view_model/single_page/daily_view_model.dart
  lib/view_model/single_page/recipe_view_model.dart
  lib/view_model/single_page/signup_view_model.dart
  lib/view_model/single_page/splash_view_model.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, renewal, viewmodel, repository, local data, view, refactoring, recipe

#89 プロバイダーで他のプロバイダーを参照するときの手順を変更
  lib/repository/local/directory/open_data_recipe_local_repository.dart
  lib/repository/local/sqlite/menus_local_repository.dart
  lib/repository/local/sqlite/schools_local_repository.dart
  lib/repository/local/sqlite/users_local_repository.dart
  lib/repository/remote/firestore_database.dart
  lib/repository/remote/menus_remote_repository.dart
  lib/repository/remote/schools_remote_repository.dart
  lib/view_model/multi_page/user_view_model.dart
  lib/view_model/single_page/calendar_view_model.dart
  lib/view_model/single_page/daily_view_model.dart
  lib/view_model/single_page/recipe_view_model.dart
  lib/view_model/single_page/signup_view_model.dart
  lib/view_model/single_page/splash_view_model.dart
  lib/view_model/single_page/terms_view_model.dart
Labels: refactoring

#100 Flutter 3.7.3への対応
  .fvm/fvm_config.json
  ios/Flutter/AppFrameworkInfo.plist
  ios/Runner.xcodeproj/project.pbxproj
  lib/model/dish/dish_model.freezed.dart
  lib/model/foodstuff/foodstuff_model.freezed.dart
  lib/model/menu/menu_model.freezed.dart
  lib/model/nutrients/nutrients_model.freezed.dart
  lib/model/quantity/quantity_model.freezed.dart
  lib/model/recipe/open_data_recipe_model.freezed.dart
  lib/model/school/school_model.freezed.dart
  lib/model/user/user_model.freezed.dart
  lib/repository/local/sqlite/local_database.dart
  lib/repository/local/sqlite/local_database.g.dart
  lib/repository/local/sqlite/menus_local_repository.dart
  lib/repository/local/sqlite/schools_local_repository.dart
  lib/repository/local/sqlite/table/dishes_table.dart
  lib/repository/local/sqlite/table/foodstuffs_table.dart
  lib/repository/remote/menus_remote_repository.dart
  lib/state/calendar/calendar_state.freezed.dart
  lib/state/daily/daily_state.freezed.dart
  lib/state/drawer/drawer_state.freezed.dart
  lib/state/signup/signup_state.freezed.dart
  lib/state/splash/splash_state.freezed.dart
  lib/state/terms/terms_state.freezed.dart
  lib/state/user/user_state.freezed.dart
  lib/view_model/multi_page/common_function.dart
  lib/view_model/multi_page/user_view_model.dart
  lib/view_model/single_page/daily_view_model.dart
  lib/view_model/single_page/signup_view_model.dart
  lib/view_model/single_page/splash_view_model.dart
  pubspec.lock
  pubspec.yaml
Labels: renewal, moor, refactoring, debug, Firestore
