Repository Hakondate/Hakondate, pull requests merged in 2024-01, with the labels that each got.

#117 ユーザー情報（お子様情報）画面の実装
  README.md
  ios/Runner.xcodeproj/project.pbxproj
  lib/constant/new_user_id.dart
  lib/router/routes.dart
  lib/state/user_settings/user_settings_state.dart
  lib/state/user_settings/user_settings_state.freezed.dart
  lib/view/component/dialog/signing_up_dialog.dart
  lib/view/component/signing_form/error_indication.dart
  lib/view/component/signing_form/name_form.dart
  lib/view/component/signing_form/school_form.dart
  lib/view/component/signing_form/submit_button.dart
  lib/view/daily/daily_drawer.dart
  lib/view/help/help_frame.dart
  lib/view/information/information.dart
  lib/view/signup/signing_up_dialog.dart
  lib/view/signup/signup.dart
  lib/view/splash/splash.dart
  lib/view/user_settings/user_delete_dialog.dart
  lib/view/user_settings/user_settings.dart
  lib/view/user_settings/user_settings_detail.dart
  lib/view/user_settings/user_switch_dialog.dart
  lib/view_model/multi_page/drawer/drawer_view_model.dart
  lib/view_model/multi_page/drawer/drawer_view_model.g.dart
  lib/view_model/multi_page/user/user_view_model.dart
  lib/view_model/multi_page/user/user_view_model.g.dart
  lib/view_model/single_page/daily/daily_view_model.dart
  lib/view_model/single_page/daily/daily_view_model.g.dart
  lib/view_model/single_page/signup/signup_view_model.dart
  lib/view_model/single_page/signup/signup_view_model.g.dart
  lib/view_model/single_page/splash/splash_view_model.dart
  lib/view_model/single_page/splash/splash_view_model.g.dart
  lib/view_model/single_page/user_settings/user_settings_view_model.dart
  lib/view_model/single_page/user_settings/user_settings_view_model.g.dart
Labels: Priority: Blocker, Type: Feature

#150 Feature/dictionary additional
  lib/model/nutrients/five_major_nutrient.dart
  lib/model/nutrients/nutrients_model.dart
  lib/repository/local/sqlite/dictionary_items/dictionary_items_local_repository.dart
  lib/router/routes.dart
  lib/state/daily/daily_state.dart
  lib/state/daily/daily_state.freezed.dart
  lib/state/dictionary/dictionary_search_state.dart
  lib/state/dictionary/dictionary_search_state.freezed.dart
  lib/util/extension/string_extension.dart
  lib/view/daily/nutrients_card.dart
  lib/view/dictionary/dictionary.dart
  lib/view/dictionary/dictionary_search.dart
  lib/view/dictionary/recommend_foodstuff.dart
  lib/view_model/single_page/daily/daily_view_model.dart
  lib/view_model/single_page/daily/daily_view_model.g.dart
  lib/view_model/single_page/dictionary/dictionary_search_view_model.dart
  lib/view_model/single_page/dictionary/dictionary_search_view_model.g.dart
  lib/view_model/single_page/dictionary/dictionary_view_model.dart
  lib/view_model/single_page/dictionary/dictionary_view_model.g.dart
Labels: Priority: Blocker, Type: Feature

#184 hotfix: DailyVMのBuildに失敗する問題の解消
  lib/view_model/multi_page/user/user_view_model.dart
  lib/view_model/multi_page/user/user_view_model.g.dart
  lib/view_model/single_page/daily/daily_view_model.dart
  lib/view_model/single_page/daily/daily_view_model.g.dart
Labels: Priority: Blocker, Type: BugFix

#149 Repositoryのデータのやり取りをTypeSafeに変更する
  .vscode/settings.json
  lib/model/dictionary/dictionary_item_model.dart
  lib/model/dictionary/dictionary_item_model.freezed.dart
  lib/model/dish/dish_category.dart
  lib/model/dish/dish_model.dart
  lib/model/foodstuff/foodstuff_model.dart
  lib/model/foodstuff/foodstuff_model.freezed.dart
  lib/model/menu/menu_model.dart
  lib/model/menu/menu_model.freezed.dart
  lib/model/origin/origin_category_model.dart
  lib/model/origin/origin_item_model.dart
  lib/model/origin/origin_item_model.freezed.dart
  lib/model/origin/origin_model.dart
  lib/model/school/school_model.dart
  lib/model/school/school_model.freezed.dart
  lib/model/user/user_model.dart
  lib/repository/local/sqlite/dictionary_items/dictionary_items_local_repository.dart
  lib/repository/local/sqlite/local_database.g.dart
  lib/repository/local/sqlite/menus/menus_local_repository.dart
  lib/repository/local/sqlite/schools/schools_local_repository.dart
  lib/repository/local/sqlite/schools/schools_local_repository.g.dart
  lib/repository/local/sqlite/table/schools_table.dart
  lib/repository/local/sqlite/users/users_local_repository.dart
  lib/repository/remote/menus/menus_remote_repository.dart
  lib/repository/remote/menus/menus_remote_repository.g.dart
  lib/repository/remote/origins/origins_remote_repository.dart
  lib/repository/remote/origins/origins_remote_repository.g.dart
  lib/repository/remote/schools/schools_remote_repository.dart
  lib/repository/remote/schools/schools_remote_repository.g.dart
  lib/view/daily/menu_card.dart
  lib/view_model/single_page/splash/splash_view_model.dart
  lib/view_model/single_page/splash/splash_view_model.g.dart
Labels: Priority: Middle, Type: Refactor
